import type { Metadata } from "next";
import { Metal } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistMetal = Metal({
  variable: "--font-metal-sans",
  subsets: ["khmer"],
  weight: "400"
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={[geistMetal.variable,'antialiased'].join(" ")}
      >
        <nav style={{ display: "flex", gap: "1rem" }}>
          <Link href="/products">products</Link>
          <Link href="/items">items</Link>
          <Link href="/">home</Link>
          <Link href="/static">stati</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
